  version: "3.7"

  services:
    caddy:
      image: caddy:latest
      restart: unless-stopped
      networks:
        - n8n-network
      ports:
        - "8080:80"  # Change to a different port
      volumes:
        - caddy_data:/data
        - ./caddy_config:/config
        - ./caddy_config/Caddyfile:/etc/caddy/Caddyfile

    postgres:
      image: postgres:16-alpine
      hostname: postgres
      networks:
        - n8n-network
      restart: unless-stopped
      environment:
        - POSTGRES_USER
        - POSTGRES_PASSWORD
        - POSTGRES_DB
      volumes:
        - postgres_storage:/var/lib/postgresql/data
      healthcheck:
        test: ['CMD-SHELL', 'pg_isready -h localhost -U ${POSTGRES_USER} -d ${POSTGRES_DB}']
        interval: 5s
        timeout: 5s
        retries: 10

    n8n-import:
      image: n8nio/n8n:latest
      hostname: n8n-import
      container_name: n8n-import
      networks:
        - n8n-network
      entrypoint: /bin/sh
      environment:
        - DB_TYPE=postgresdb
        - DB_POSTGRESDB_HOST=postgres
        - DB_POSTGRESDB_USER=${POSTGRES_USER}
        - DB_POSTGRESDB_PASSWORD=${POSTGRES_PASSWORD}
        - N8N_DIAGNOSTICS_ENABLED=false
        - N8N_PERSONALIZATION_ENABLED=false
        - N8N_ENCRYPTION_KEY
        - N8N_USER_MANAGEMENT_JWT_SECRET
      command:
        - "-c"
        - "n8n import:credentials --separate --input=/backup/credentials && n8n import:workflow --separate --input=/backup/workflows"
      volumes:
        - ./n8n/backup:/backup
      depends_on:
        postgres:
          condition: service_healthy

    n8n:
      image: n8nio/n8n:latest
      hostname: n8n
      container_name: n8n
      networks: 
        - n8n-network
      restart: unless-stopped
      environment:
        - DB_TYPE=postgresdb
        - DB_POSTGRESDB_HOST=postgres
        - DB_POSTGRESDB_USER=${POSTGRES_USER}
        - DB_POSTGRESDB_PASSWORD=${POSTGRES_PASSWORD}
        - N8N_DIAGNOSTICS_ENABLED=false
        - N8N_PERSONALIZATION_ENABLED=false
        - N8N_ENCRYPTION_KEY
        - N8N_USER_MANAGEMENT_JWT_SECRET
        - N8N_HOST=${SUBDOMAIN}.${DOMAIN_NAME}
        - N8N_PORT=${PORT}
        - N8N_PROTOCOL=http
        - NODE_ENV=production
        - WEBHOOK_URL=https://${SUBDOMAIN}.${DOMAIN_NAME}/
        - GENERIC_TIMEZONE=${GENERIC_TIMEZONE}
        - N8N_SECURE_COOKIE=false
      volumes:
        - n8n_storage:/home/node/.n8n
        - ./n8n/backup:/backup
        - ./shared:/data/shared
        - ${DATA_FOLDER}/local_files:/files
      depends_on:
        postgres:
          condition: service_healthy
        n8n-import:
          condition: service_completed_successfully

  volumes:
    caddy_data:
      external: true
    n8n_storage:
    postgres_storage:

  networks:
    n8n-network: